name: 'Setup Cache'
description: 'Setup npm and Turbo cache'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/cache@v4
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/cache@v4
      with:
        path: .turbo
        key: turbo-${{ github.sha }}
        restore-keys: turbo-